### GET /
GET http://localhost:5003

### resgister /auth/register
POST http://localhost:5003/auth/register 
Content-Type:application/json

{
    "username":"darren@gmail.com",
    "password":"123456"
}

### login a user 
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "darren@gmail.com",
    "password":"123456"

}


### FETCH all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY5ODcwNjcxLCJleHAiOjE3Njk5NTcwNzF9.JsY6PcBD-5womvV8xEecLsSslOeN5AwkNZYcX5x_3bY
// middleware can use token to let us through

### CREATE A NEW TODO post /todos
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwMTMzODc2LCJleHAiOjE3NzAyMjAyNzZ9.f1kHk1WGByQIaNlo5Vgvaxzm3s-ybN_KTStFdw-g5PM

{
    "task":"Get FAANG"

}

### Update a todo PUT /todos/id
PUT http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY5ODcwNjcxLCJleHAiOjE3Njk5NTcwNzF9.JsY6PcBD-5womvV8xEecLsSslOeN5AwkNZYcX5x_3bY
Content-Type: application/json

{
    "completed": true
}


### DELETE a todo DELETE  /todos/id  , hard delete (not recco)
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY5ODcwNjcxLCJleHAiOjE3Njk5NTcwNzF9.JsY6PcBD-5womvV8xEecLsSslOeN5AwkNZYcX5x_3bY


